version: '3'

services:
  poller:
    build: .
    command: bash -c "node /http-worker/conductor-poller/start-conductor-poller.js"
    depends_on:
      - worker

  worker:
    build: .
    command: bash -c "node /http-worker/http-worker/httpworker-grpc-server"
    ports:
      - "50051:50051"
